# create array :-

In [3]:
import numpy as np 
array=np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# dimensional array :-

In [5]:
# 0-D array
import numpy as np
array=np.array(24)
print(array)

24


In [7]:
# 1-D arary
import numpy as np
array=np.array([23,45,67,89])
print(array)

[23 45 67 89]


In [9]:
# 2-D array
import numpy as np
array=np.array([[1,3,5],[2,4,6]])
print(array)

[[1 3 5]
 [2 4 6]]


In [12]:
# 3-D array
import numpy as np
array=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


# check no. of dimensions
# ndim (function) 

In [14]:
import numpy as np 
array1=np.array(34)
array2=np.array([1,2,3])
array3=np.array([[2,4,6],[1,3,5]])
array4=np.array([[[23,34,45],[56,78,98]],[[12,45,23],[56,67,78]]])
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)

0
1
2
3


# higher dimensional arrays 
# ndmin ()

In [20]:
import numpy as np
array=np.array([1,2,3,4],ndmin=5)
print(array)
print('number of dimension',array.ndim)

[[[[[1 2 3 4]]]]]
number of dimension 5


# Indexing of array
# access array element :-

In [27]:
import numpy as np
array=np.array([23,45,67,89])
print(array[2])
print(array[1]+[2])
print(array[2]+[3])

67
[47]
[70]


# access 2-D array :-


In [32]:
import numpy as np
array=np.array([[10,20,30,40,50,60,70,80,90],[12,23,34,45,56,67,78,32,66]])
print(array[1,5])

67


# access 3-D array :-

In [35]:
import numpy as np
array=np.array([[[1,2,3,4,5,6,7,8,9,10],[2,4,6,8,10,12,14,16,18,20],[1,3,5,7,9,11,13,15,17,19]]])
print(array[0,2,4])

9


# array slicing :-

In [38]:
import numpy as np
array=np.array([23,45,67,89,12,34,45,78,56,65,87,90,10])
print(array[1:6])
print(array[:4])
print(array[4:])

[45 67 89 12 34]
[23 45 67 89]
[12 34 45 78 56 65 87 90 10]


# Negative slicing :-

In [39]:
import numpy as np
array=np.array([23,45,67,89,12,34,45,78,56,65,87,90,10])
print(array[-4:-1])

[65 87 90]


# Step:-

In [45]:
import numpy as np
array=np.array([23,45,67,89,12,34,45,78,56,65,87,90,10])
print(array[1:58:2]) # starting : ending : step
print(array[::2]) # starting : step

[45 89 34 78 65 90]
[23 67 12 45 56 87 10]


# 2-D array slicing :-

In [62]:
import numpy as np
array=np.array([[10,20,30,40,50,60,70,80,90],[12,23,34,45,56,67,78,32,66]])
print(array[1,1:8])
print(array[0,:5])
print(array[1,7:])
print(array[0:3,3])
print(array[0:2,1:4])

[23 34 45 56 67 78 32]
[10 20 30 40 50]
[32 66]
[40 45]
[[20 30 40]
 [23 34 45]]


# check data type 
# dtype()

In [74]:
import numpy as np
array=np.array([23,45,67,89])
print('array data type =',array.dtype)

array1=np.array(['apple','banana','cherry'])
print('array 1 data type =',array1.dtype)

array2=np.array([1,2,3,4],dtype='S')
print('array2 =',array2,' data type =',array2.dtype)

array3=np.array([1,2,3,4,5],dtype='i4')
print('array3 =',array3,' data type =',array3.dtype)

array data type = int32
array 1 data type = <U6
array2 = [b'1' b'2' b'3' b'4']  data type = |S1
array3 = [1 2 3 4 5]  data type = int32


# astype ()

In [79]:
import numpy as np
array=np.array([1.1,2.1,3.1,4.1])
newarr=array.astype('i')
print('newarr =',newarr, 'data type =',newarr.dtype)

array1=np.array([1.1,2.1,3.1,4.1])
newarr1=array1.astype(int)
print('newarr1 =',newarr1, 'data type =',newarr1.dtype)

array2=np.array([1,0,3,4])
newarr2=array2.astype(bool)
print('newarr2 =',newarr2, 'data type =',newarr2.dtype)

newarr = [1 2 3 4] data type = int32
newarr1 = [1 2 3 4] data type = int32
newarr2 = [ True False  True  True] data type = bool


# copy vs view :-

In [81]:
import numpy as np
array=np.array([1,2,3,4])
x=array.copy()
array[2]=42
print(array)
print(x)

[ 1  2 42  4]
[1 2 3 4]


In [83]:
import numpy as np
array=np.array([1,2,3,4])
x=array.view()
array[2]=34
print(array)
print(x)

[ 1  2 34  4]
[ 1  2 34  4]


# array shape :-

In [85]:
import numpy as np
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array.shape)

(2, 5)


In [88]:
import numpy as np
array=np.array([1,2,3,4,5],ndmin=3)
print(array,'shape of array =',array.shape)

[[[1 2 3 4 5]]] shape of array = (1, 1, 5)


# reshape :-


# 1-D to 2-D :-

In [102]:
import numpy as np
array=np.array([23,45,67,89,12,34,45,78,56,65,87,90])
newarr=array.reshape(2,6)
print(newarr)

[[23 45 67 89 12 34]
 [45 78 56 65 87 90]]


# 1-D to 3-D :-

In [106]:
import numpy as np
array=np.array([23,45,67,89,12,34,45,78,56,65,87,90])
newarr=array.reshape(3,2,2)
print(newarr)

[[[23 45]
  [67 89]]

 [[12 34]
  [45 78]]

 [[56 65]
  [87 90]]]


# any dimensional array to 1-D 
# reshape(-1)

In [108]:
import numpy as np
array=np.array([[[1,2,3,4,5,6,7,8,9,10],[2,4,6,8,10,12,14,16,18,20],[1,3,5,7,9,11,13,15,17,19]]])
newarr=array.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10  2  4  6  8 10 12 14 16 18 20  1  3  5  7
  9 11 13 15 17 19]
