In [2]:
# Array=An array is a central data structure of the NumPy library.
# An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. 
# It has a grid of elements that can be indexed in various ways.

# Type of Array :-
#     - 1D = The One-dimensional array contains elements only in one dimension. 
#            In other words, the shape of the NumPy array should contain only one value in the tuple.

#     - 2D = A 2D array is an array of arrays that can be represented in matrix form, like rows and columns. 
#            In this array, the position of data elements is defined with two indices instead of a single index. 
#            In Python, we can access two-dimensional array elements using two indices.

#     - 3D=  Arrays in NumPy are data structures with high performance suitable for mathematical operations.
#            The three levels of arrays nested inside one another represent the three-dimensional array in Python, where each level means one dimension.


# import array as n
# n.array.

In [5]:
# numpy( 1D array) :-
import numpy as ny
array1=ny.array([12,23,34,45,54,56,87])
print(array1)
print(type(array1))

[12 23 34 45 54 56 87]
<class 'numpy.ndarray'>


In [7]:
# 2D array :-
array2=ny.array([[2,4,6,8,10],[1,3,5,7,9],[11,12,13,14,15]])
print(array2)
print("element catch by indexing in 2D Array :",array2[1,3]) # array2[row,column]

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [11 12 13 14 15]]
element catch by indexing in 2D Array : 7


In [9]:
# 3D array :-
array3=ny.array([[[1,3,5,7,9],[2,4,6,8,10],[1,8,27,64,125]]])
print(array3)
print("element catch by indexing in 3D Array :",array3[0][2][4]) # array3[row,column,row]

[[[  1   3   5   7   9]
  [  2   4   6   8  10]
  [  1   8  27  64 125]]]
element catch by indexing in 3D Array : 125


# Practice Questions :-

In [184]:
# Sum :-
import numpy as np
arr=np.array([12,23,34,45,56,67,78,89,90])
sum=0
for i in arr:
    sum=sum+i
print("Sum Of All Element :",sum)

Sum Of All Element : 494


In [185]:
# Max. and Min. :-
arr1=np.array([12,23,34,45,56,67,78,89,90])
def Maximum(arr1):
    Max=arr1[0]
    for i in arr1:
        if Max > i:
            Max=i
    return Max
def Minimum(arr1):
    Min=arr1[0]
    for i in arr1:
        if Min < i:
            Min=i
    return Min
print("Maximum element is :",Maximum(arr1))
print("Minimum element is :",Minimum(arr1))     

Maximum element is : 12
Minimum element is : 90


In [186]:
# 2nd highest :-
arr2=np.array([12,23,34,45,56,67,78,89,90])
for i in range(len(arr2)):
    for j in range(len(arr2)-1-i):
        if(arr2[j]>arr2[j+1]):
            t=arr2[j]
            arr2[j]=arr2[j+1]
            arr2[j+1]=t
print("Sorting of Array :",arr2)
print("2nd Highest element of Array :",arr2[-2])

Sorting of Array : [12 23 34 45 56 67 78 89 90]
2nd Highest element of Array : 89


In [188]:
# Sort :-
arr3=np.array([4,1,6,7,89,87,65,67,34,12,23,43,90,54,58,68,99])
for i in range(len(arr3)):
    for j in range(len(arr3)-1-i):
        if(arr3[j]>arr3[j+1]):
            t=arr3[j]
            arr3[j]=arr3[j+1]
            arr3[j+1]=t
print("Sorting Of Array :",arr3)

Sorting Of Array : [ 1  4  6  7 12 23 34 43 54 58 65 67 68 87 89 90 99]


In [189]:
# Swaping Single Dimensional Array :-
import numpy as py
array1=py.array([1,2,3,4,5,6,7,8,9])
array2=py.array([10,11,12,13,14,15])
t=array1
array1=array2
array2=t
print("After Swaping single Array :-")
print("Array1 :",array1)
print("Array2 :",array2)

After Swaping single Array :-
Array1 : [10 11 12 13 14 15]
Array2 : [1 2 3 4 5 6 7 8 9]


# Functions :-

In [192]:
# How to check array dimension(1D, 2D and 3D) :-
array1=ny.array([12,23,34,45,54,56,87])
array2=ny.array([[2,4,6,8,10],[1,3,5,7,9],[11,12,13,14,15]])
array3=ny.array([[[1,3,5,7,9],[2,4,6,8,10],[1,8,27,64,125]]])
print(array3.ndim)
print(array1.ndim)
print(array2.ndim)

3
1
2


In [194]:
# How to check shape(Row,column)of array :-
array1=ny.array([12,23,34,45,54,56,87])
array2=ny.array([[2,4,6,8,10],[1,3,5,7,9],[11,12,13,14,15]])
array3=ny.array([[[1,3,5,7,9],[2,4,6,8,10],[1,8,27,64,125]]])
print(array3.shape)
print(array1.shape)
print(array2.shape)

(1, 3, 5)
(7,)
(3, 5)


In [196]:
# HoW to reshape of array :-
import numpy as ny
ar=ny.array([12,23,34,4,5,56,67,78,89,54,43,23,32,12,67,34])
print("Array :",ar)
k=ar.reshape(1,4,4)
print("single array into 3D :\n",k)
k=ar.reshape(4,4)
print("single array into 2D :\n",k)

Array : [12 23 34  4  5 56 67 78 89 54 43 23 32 12 67 34]
single array into 3D :
 [[[12 23 34  4]
  [ 5 56 67 78]
  [89 54 43 23]
  [32 12 67 34]]]
single array into 2D :
 [[12 23 34  4]
 [ 5 56 67 78]
 [89 54 43 23]
 [32 12 67 34]]


In [198]:
# access the array element :-
x=ny.array([12,23,21,34,45,56,67,87,89,90,61])
print("Indexing :-")
print("first 6th element of array :",x[5]) # 56
print("last 2nd element of array :",x[-2]) # 90
print("Slicing :-")
print("first 3rd element to 7th element of array :",x[2:7]) # 21,34,45,56,67
print("first 2nd to len(array) :",x[1:]) # 23 to len(x)
print("beggining to 7th element :",x[:8]) # 12 to 87
print("beggining to last -5th element :",x[:-4])

Indexing :-
first 6th element of array : 56
last 2nd element of array : 90
Slicing :-
first 3rd element to 7th element of array : [21 34 45 56 67]
first 2nd to len(array) : [23 21 34 45 56 67 87 89 90 61]
beggining to 7th element : [12 23 21 34 45 56 67 87]
beggining to last -5th element : [12 23 21 34 45 56 67]


In [200]:
# copy :-
x=ny.array([49,67,78,89,90,23,56,84])
k=x.copy()
print("k :",k)

# change value in x :-
x[1]=15
print("x :",x)
print("k :",k)

k : [49 67 78 89 90 23 56 84]
x : [49 15 78 89 90 23 56 84]
k : [49 67 78 89 90 23 56 84]


In [202]:
# View :-
x=ny.array([10,15,20,25,30,35,40,45,50])
k=x.view()
x[3]=100
print("x :",x)
print("k :",k)

x : [ 10  15  20 100  30  35  40  45  50]
k : [ 10  15  20 100  30  35  40  45  50]


In [264]:
# Iterate :-
x=ny.array([1,2,3,4,5,6,7,8,9,10])
for i in x:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [206]:
# Iterating on Each Scalar Element :-
a=ny.array([[10,20,30],[40,50,60],[60,70,80]])
print(a)
# for i in range(0,3):
#     for j in range(0,3):
#         print(a[i][j])
for i in ny.nditer(a):
    print(i)   

[[10 20 30]
 [40 50 60]
 [60 70 80]]
10
20
30
40
50
60
60
70
80


In [208]:
# Iterating Array With Different Data Types :-
a=ny.array([1,2,3,4])
for i in ny.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(i)
print(a.dtype)
print(i.dtype)

b'1'
b'2'
b'3'
b'4'
int32
|S11


In [265]:
# Iterating With Different Step Size :-
a=ny.array([[1,2,3],[4,5,6],[7,8,9]])
for i in ny.nditer(a[:,::2]):
    print(i)

1
3
4
6
7
9


In [263]:
# join two array :-
x=ny.array([2,4,6,8,10,12,14,16,18,20])
y=ny.array([1,3,5,7,9,11,13,15,17,19])
z=ny.concatenate((x,y))
print("z :",z)

p=ny.array([[10,20,30],[40,50,60],[70,80,90]])
q=ny.array([[1,2,3],[4,5,6],[7,8,9]])
r=ny.concatenate((p,q),axis=0)
print("r :",r)
s=ny.concatenate((p,q),axis=1)
print("s :",s)
t=ny.concatenate((p,q),axis=None)
print("t :",t)

z : [ 2  4  6  8 10 12 14 16 18 20  1  3  5  7  9 11 13 15 17 19]
r : [[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
s : [[10 20 30  1  2  3]
 [40 50 60  4  5  6]
 [70 80 90  7  8  9]]
t : [10 20 30 40 50 60 70 80 90  1  2  3  4  5  6  7  8  9]


In [214]:
# split :-
print("split :-")
p=ny.array([12,33,34,56,84,15,32,45])
q=ny.array_split(p,4)
print("q :\n",q)

# split along row :-
print("split along row :-")
p=ny.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
x=ny.hsplit(p,3)
print("x :\n",x)

# split along columns :-
print("split along column :-")
y=ny.vsplit(p,5)
print("y :\n",y)

split :-
q :
 [array([12, 33]), array([34, 56]), array([84, 15]), array([32, 45])]
split along row :-
x :
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15]])]
split along column :-
y :
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]]), array([[13, 14, 15]])]


In [216]:
# Where :- 
p=ny.array([34,45,34,34,23,45,56,78,84,75])
q=ny.where(p>=40,p,p*2)
print("q :",q)

q : [68 45 68 68 46 45 56 78 84 75]


In [218]:
# where = used for searching element :-
p=ny.array([12,23,34,12,56,67,12,12,78])
x=ny.where(p==12)
y=ny.where(p%2==0)
z=ny.where(p%3==1)
print("x :",x)
print("y :",y)
print("z :",z)

x : (array([0, 3, 6, 7], dtype=int64),)
y : (array([0, 2, 3, 4, 6, 7, 8], dtype=int64),)
z : (array([2, 5], dtype=int64),)


In [220]:
# Filter :-
print("1st Method :-")
x=ny.array([34,56,84,52,75,45,52,21])
y=[False,True,True,True,False,False,True,False]
k=x[y]
print("k :",k)

print("2nd Method :-")
p=ny.array([13,5,345,64,756,45,56,12,87,45,89,90,33])
q=[]
for i in p:
    if (i>50):
        q.append(True)
    else:
        q.append(False)
r=p[q]
print("r :",r)

1st Method :-
k : [56 84 52 52]
2nd Method :-
r : [345  64 756  56  87  89  90]


In [222]:
# Enumerated Iteration Using ndenumerate() :- 
# index number(row,column)
print("1D array :-")
a=ny.array([12,2,34,45,56,67,78,32])
for i in ny.ndenumerate(a):
    print(i) 
    
print("2D array :-")
a=ny.array([[10,20,30],[20,10,15],[12,23,34]])
for i in ny.ndenumerate(a):
    print(i) # 

1D array :-
((0,), 12)
((1,), 2)
((2,), 34)
((3,), 45)
((4,), 56)
((5,), 67)
((6,), 78)
((7,), 32)
2D array :-
((0, 0), 10)
((0, 1), 20)
((0, 2), 30)
((1, 0), 20)
((1, 1), 10)
((1, 2), 15)
((2, 0), 12)
((2, 1), 23)
((2, 2), 34)


In [224]:
# stack Function :-
ar1=ny.array([10,13,16,19,20,35])
ar2=ny.array([43,26,28,89,76,64])
array1=ny.stack((ar1,ar2),axis=1)
print('array1 :\n',array1)

# horizontaly stack :-
array2=ny.hstack((ar1,ar2))
print('array2 :\n',array2)

# verticaly stack :-
array3=ny.vstack((ar1,ar2))
print('array3 :\n',array3)

# along hight (depth) :-
array4=ny.dstack((ar1,ar2))
print('array4 :\n',array4)

array1 :
 [[10 43]
 [13 26]
 [16 28]
 [19 89]
 [20 76]
 [35 64]]
array2 :
 [10 13 16 19 20 35 43 26 28 89 76 64]
array3 :
 [[10 13 16 19 20 35]
 [43 26 28 89 76 64]]
array4 :
 [[[10 43]
  [13 26]
  [16 28]
  [19 89]
  [20 76]
  [35 64]]]


In [21]:
# Random Function :-
from numpy import random
print("integer number :-")
x=random.randint(10)
print(x)
x1=random.randint(1,10)
print(x1)
x2=random.randint(10,30,5)
print(x2)
print("float number :-")
y=random.rand()
print(y)
print("1D array :-")
z=random.rand(5)
print(z)
print("2D array :-")
p=random.rand(2,4)
print(p)
print("3D array :-")
q=random.rand(1,3,4)
print(q)

integer number :-
2
6
[22 12 23 28 24]
float number :-
0.15219425047557122
1D array :-
[0.7108257  0.46503756 0.46906269 0.12108832 0.93815732]
2D array :-
[[0.1362122  0.72446998 0.18597907 0.20810784]
 [0.75107241 0.17113604 0.66151987 0.66587211]]
3D array :-
[[[0.0532329  0.08318536 0.89329539 0.85513015]
  [0.14884287 0.50635705 0.98488732 0.29248219]
  [0.61096094 0.43596504 0.77841677 0.54941048]]]


In [229]:
# choice Function :-
x=random.choice([34,56,67,34,23,56,67,34,83,23])
print("x :",x)
y=random.choice([34,56,67,34,23,56,67,34,83,23],size=(3,4))
print("y :\n",y)
z=random.choice([34,56,67,34,23,56,67,34,83,23],size=(1,4,5))
print("z :\n",z)

x : 23
y :
 [[34 56 67 34]
 [67 56 23 34]
 [34 56 56 67]]
z :
 [[[56 67 67 23 23]
  [56 23 67 56 56]
  [23 34 56 83 23]
  [67 67 34 56 34]]]


In [243]:
# random data distribution :-
from numpy import random
x=random.choice([12,5,7,3,24], p=[0.1,0.4,0.3,0.2,0.0],size=(50))
print("1D array :\n",x)

y=random.choice([12,5,7,3,24], p=[0.1,0.4,0.3,0.2,0.0],size=(2,4))
print("2D array :\n",y)

z=random.choice([12,5,7,3,24], p=[0.1,0.4,0.3,0.2,0.0],size=(1,5,3))
print("3D array :\n",z)

1D array :
 [ 7  7  3  5  5  5  7  7  7  5 12  5  5 12  7  5  5  5  3  5  7  5  7  3
  3 12  5  7  5  7  7  7  5  7  3  7  7  3  7  5  7  5  7  3  7  5  5  5
  7  5]
2D array :
 [[5 3 5 5]
 [7 5 3 5]]
3D array :
 [[[ 5  7  5]
  [12  3  3]
  [ 5  5  7]
  [ 7  5  5]
  [ 5  3  5]]]


In [269]:
# shuffle function :-
from numpy import random 
import numpy as ny
x=ny.array([1,2,3,4,5,6,7,8,9,10])
random.shuffle(x)
print(x)

[ 7 10  9  1  3  5  4  2  6  8]


In [399]:
# Permutation Function :-
from numpy import random 
import numpy as ny
x=ny.array([1,2,3,4,5,6,7,8,9,10])
print(random.permutation(x))

[ 6  5  3 10  2  1  7  8  4  9]
