In [1]:
import numpy as np

In [2]:
li=[23,34,45,56,67]
li

[23, 34, 45, 56, 67]

In [3]:
ar=np.array(li)
ar

array([23, 34, 45, 56, 67])

In [4]:
type(ar)

numpy.ndarray

In [5]:
l=[1,2,3,4,6.4,5.4,'a',True,3+2j]

In [6]:
ar1=np.array(l)
print(ar1)
print(type(ar1))
ar1.dtype

['1' '2' '3' '4' '6.4' '5.4' 'a' 'True' '(3+2j)']
<class 'numpy.ndarray'>


dtype('<U64')

In [7]:
ar1.ndim

1

In [8]:
print(ar1.shape)
print(len(ar1))
ar1.size

(9,)
9


9

In [9]:
L=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [10]:
a=np.array(L)

In [11]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
a.shape

(4, 3)

In [13]:
a.ndim

2

In [14]:
print(a.size)
print(a.shape)
len(a)

12
(4, 3)


4

In [15]:
A=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

In [16]:
ar3=np.array(A)

In [17]:
ar3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
print(ar3.shape)
print(ar3.size)
len(ar3)

(2, 2, 3)
12


2

In [19]:
print(ar3.ndim)
ar3.strides

3


(24, 12, 4)

In [20]:
np.zeros(4,dtype=int,order='F')

array([0, 0, 0, 0])

In [21]:
Z=np.zeros((5,3),dtype=float,order="F")
print(Z)
Z.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [22]:
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
z=np.zeros((2,3,2),dtype=int,order="C")
z

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [24]:
c=np.ones((2,3,4),dtype=str)
c

array([[['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']],

       [['1', '1', '1', '1'],
        ['1', '1', '1', '1'],
        ['1', '1', '1', '1']]], dtype='<U1')

In [25]:
np.full((2,4,8),456,dtype=int)

array([[[456, 456, 456, 456, 456, 456, 456, 456],
        [456, 456, 456, 456, 456, 456, 456, 456],
        [456, 456, 456, 456, 456, 456, 456, 456],
        [456, 456, 456, 456, 456, 456, 456, 456]],

       [[456, 456, 456, 456, 456, 456, 456, 456],
        [456, 456, 456, 456, 456, 456, 456, 456],
        [456, 456, 456, 456, 456, 456, 456, 456],
        [456, 456, 456, 456, 456, 456, 456, 456]]])

In [26]:
np.full((3,2,4),3.14)

array([[[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14]]])

In [27]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
a=np.arange(0,201,20,dtype=int)
a

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [29]:
A=np.arange(20,-21,-4)
print(A)
A.sum()

[ 20  16  12   8   4   0  -4  -8 -12 -16 -20]


0

In [30]:
print(np.linspace(10,20,9,endpoint=False,dtype=int))
np.linspace(20,30,8,endpoint=False,dtype=float,retstep=True)

[10 11 12 13 14 15 16 17 18]


(array([20.  , 21.25, 22.5 , 23.75, 25.  , 26.25, 27.5 , 28.75]), 1.25)

In [31]:
np.logspace(10,100,2,base=10)

array([1.e+010, 1.e+100])

In [32]:
np.geomspace(1,20,10)

array([ 1.        ,  1.39495079,  1.94588772,  2.71441762,  3.78647901,
        5.2819519 ,  7.368063  , 10.27808533, 14.33742329, 20.        ])

In [33]:
b=np.array((23,45,78,98))
print(type(b))
b

<class 'numpy.ndarray'>


array([23, 45, 78, 98])

In [34]:
a=np.array({1,2,3,4,5,6,7,8,9,1,1,1,1})
print(a)
print(a.ndim)
a.shape
type(a)

{1, 2, 3, 4, 5, 6, 7, 8, 9}
0


numpy.ndarray

In [35]:
c=np.array({1:23,2:46})
print(c.ndim)
c

0


array({1: 23, 2: 46}, dtype=object)

In [36]:
n1=np.arange(1,31)
n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
np.reshape(n1,(5,6))
n1.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
a=n1.reshape(5,3,2,order='F')
a

array([[[ 1, 16],
        [ 6, 21],
        [11, 26]],

       [[ 2, 17],
        [ 7, 22],
        [12, 27]],

       [[ 3, 18],
        [ 8, 23],
        [13, 28]],

       [[ 4, 19],
        [ 9, 24],
        [14, 29]],

       [[ 5, 20],
        [10, 25],
        [15, 30]]])

In [39]:
np.reshape(n1,(1,3,10))

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]])

In [40]:
mat=np.reshape(n1,(3,2,5),order="F")
mat

array([[[ 1,  7, 13, 19, 25],
        [ 4, 10, 16, 22, 28]],

       [[ 2,  8, 14, 20, 26],
        [ 5, 11, 17, 23, 29]],

       [[ 3,  9, 15, 21, 27],
        [ 6, 12, 18, 24, 30]]])

In [41]:
print(mat.shape)
mat.size

(3, 2, 5)


30

In [42]:
mat.reshape(5,6,order="F")

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [43]:
A1=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
print(A1)
Z1=A1
S=np.reshape(Z1,(2,2,3))
print(S)
E=S.flatten()
print(type(E))
print(E)
E.ndim

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12]


1

In [44]:
print(mat)
mat.flatten()

[[[ 1  7 13 19 25]
  [ 4 10 16 22 28]]

 [[ 2  8 14 20 26]
  [ 5 11 17 23 29]]

 [[ 3  9 15 21 27]
  [ 6 12 18 24 30]]]


array([ 1,  7, 13, 19, 25,  4, 10, 16, 22, 28,  2,  8, 14, 20, 26,  5, 11,
       17, 23, 29,  3,  9, 15, 21, 27,  6, 12, 18, 24, 30])

In [45]:
S.flatten()
a=list(S.flatten())

print(type(a))
a

<class 'list'>


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [46]:
ar=np.random.randint(5,11,24)
ar

array([ 7,  8,  8,  9, 10,  8,  6,  5,  5,  9,  9,  6, 10,  8,  7,  6, 10,
       10,  9,  7, 10,  5, 10,  8])

In [47]:
ar=np.random.random(24)
ar

array([0.00452787, 0.55697906, 0.18638676, 0.79915618, 0.12667585,
       0.61499027, 0.44344845, 0.77640317, 0.71653316, 0.90020207,
       0.08481457, 0.8482417 , 0.11467355, 0.23264375, 0.22634707,
       0.29056631, 0.35455165, 0.28742429, 0.08906501, 0.99596979,
       0.22595245, 0.5472452 , 0.42050061, 0.3224515 ])

In [48]:
import random
list1 = [1, 2, 3, 4, 5, 6]
print(random.choices(list1,k=10))

[4, 6, 3, 1, 1, 4, 5, 5, 4, 1]


In [49]:
import numpy as np
np.unique(ar)

array([0.00452787, 0.08481457, 0.08906501, 0.11467355, 0.12667585,
       0.18638676, 0.22595245, 0.22634707, 0.23264375, 0.28742429,
       0.29056631, 0.3224515 , 0.35455165, 0.42050061, 0.44344845,
       0.5472452 , 0.55697906, 0.61499027, 0.71653316, 0.77640317,
       0.79915618, 0.8482417 , 0.90020207, 0.99596979])

In [50]:
print(ar.tolist())
T=ar.reshape(3,4,2,order='F')
print(T)
T.tolist()

[0.004527873758177536, 0.5569790608958286, 0.1863867597198492, 0.7991561800798876, 0.12667584868742865, 0.6149902659344282, 0.44344844519831006, 0.776403166131415, 0.7165331583273374, 0.9002020721582946, 0.0848145748892355, 0.8482417010335207, 0.11467355155463588, 0.2326437472630163, 0.22634707123216702, 0.29056630623073865, 0.35455165465408955, 0.2874242923787612, 0.08906500539533346, 0.9959697922417722, 0.22595244640998602, 0.5472452013382967, 0.4205006093359729, 0.3224515032797266]
[[[0.00452787 0.11467355]
  [0.79915618 0.29056631]
  [0.44344845 0.08906501]
  [0.90020207 0.5472452 ]]

 [[0.55697906 0.23264375]
  [0.12667585 0.35455165]
  [0.77640317 0.99596979]
  [0.08481457 0.42050061]]

 [[0.18638676 0.22634707]
  [0.61499027 0.28742429]
  [0.71653316 0.22595245]
  [0.8482417  0.3224515 ]]]


[[[0.004527873758177536, 0.11467355155463588],
  [0.7991561800798876, 0.29056630623073865],
  [0.44344844519831006, 0.08906500539533346],
  [0.9002020721582946, 0.5472452013382967]],
 [[0.5569790608958286, 0.2326437472630163],
  [0.12667584868742865, 0.35455165465408955],
  [0.776403166131415, 0.9959697922417722],
  [0.0848145748892355, 0.4205006093359729]],
 [[0.1863867597198492, 0.22634707123216702],
  [0.6149902659344282, 0.2874242923787612],
  [0.7165331583273374, 0.22595244640998602],
  [0.8482417010335207, 0.3224515032797266]]]

In [51]:
a1=np.random.randint(10,100,7)
a2=np.random.randint(10,100,5)
a3=np.random.randint(10,100,5)

In [52]:
a1

array([50, 38, 80, 78, 42, 20, 94])

In [53]:
print(a2)
a3

[98 75 74 73 48]


array([39, 25, 29, 15, 18])

In [54]:
np.concatenate((a1,a2,a3),axis=0)

array([50, 38, 80, 78, 42, 20, 94, 98, 75, 74, 73, 48, 39, 25, 29, 15, 18])

In [55]:
mat1=np.random.randint(10,100,20).reshape(5,4)
mat1

array([[20, 47, 86, 65],
       [21, 27, 17, 32],
       [40, 86, 47, 69],
       [20, 32, 91, 76],
       [54, 44, 46, 81]])

In [56]:
mat2=np.random.randint(10,100,30).reshape(5,6)
mat2

array([[31, 90, 31, 55, 97, 92],
       [86, 95, 21, 13, 65, 12],
       [21, 87, 82, 39, 25, 54],
       [97, 49, 25, 70, 35, 87],
       [46, 88, 53, 94, 25, 64]])

In [57]:
np.concatenate((mat1,mat2),axis=1)

array([[20, 47, 86, 65, 31, 90, 31, 55, 97, 92],
       [21, 27, 17, 32, 86, 95, 21, 13, 65, 12],
       [40, 86, 47, 69, 21, 87, 82, 39, 25, 54],
       [20, 32, 91, 76, 97, 49, 25, 70, 35, 87],
       [54, 44, 46, 81, 46, 88, 53, 94, 25, 64]])

In [58]:
q1=np.random.randint(50,100,20).reshape(5,4)
print(q1)
print("\n\n")
q2=np.random.randint(0,50,24).reshape(6,4)
print(q2)
print("\n\n")

Q=np.concatenate((q1,q2),axis=0)
print(Q)

[[51 51 66 86]
 [74 81 85 51]
 [50 96 93 95]
 [64 65 69 80]
 [61 65 90 57]]



[[27 22 21 43]
 [16 29 12  2]
 [30 30 40 47]
 [12  8 23 41]
 [44 46 13  5]
 [13 14 10  8]]



[[51 51 66 86]
 [74 81 85 51]
 [50 96 93 95]
 [64 65 69 80]
 [61 65 90 57]
 [27 22 21 43]
 [16 29 12  2]
 [30 30 40 47]
 [12  8 23 41]
 [44 46 13  5]
 [13 14 10  8]]


In [59]:
Q.tolist()

[[51, 51, 66, 86],
 [74, 81, 85, 51],
 [50, 96, 93, 95],
 [64, 65, 69, 80],
 [61, 65, 90, 57],
 [27, 22, 21, 43],
 [16, 29, 12, 2],
 [30, 30, 40, 47],
 [12, 8, 23, 41],
 [44, 46, 13, 5],
 [13, 14, 10, 8]]

In [60]:
ar1=np.random.randint(10,100,30)

In [61]:
ar1

array([65, 92, 93, 43, 80, 50, 69, 50, 16, 79, 98, 66, 91, 76, 85, 18, 85,
       28, 99, 95, 85, 87, 15, 60, 93, 44, 50, 30, 24, 85])

In [62]:
ar1[3]

43

In [63]:
ar1[2]

93

In [64]:
ar1[-2]

24

In [65]:
ar1[-30]

65

In [66]:
ar1[2:9:2]

array([93, 80, 69, 16])

In [67]:
mat2

array([[31, 90, 31, 55, 97, 92],
       [86, 95, 21, 13, 65, 12],
       [21, 87, 82, 39, 25, 54],
       [97, 49, 25, 70, 35, 87],
       [46, 88, 53, 94, 25, 64]])