# NumPy ufuncs (Universal Functions) :-

In [ ]:
# What is ufuncs ?
# ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

In [ ]:
# Why use ufuncs?
# ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

# They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

# ufuncs also take additional arguments, like:

# where boolean array or condition defining where the operations should take place.

# dtype defining the return type of elements.

# out output array where the return value should be copied.

# How to create own functions :-

In [ ]:
# To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

# The frompyfunc() method takes the following arguments:

# function - the name of the function.
# inputs - the number of input arguments (arrays).
# outputs - the number of output arrays.

In [28]:
# Create your own ufunc for addition:
import numpy as np
def myadd(x, y):
  return x+y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [30]:
# Check if a Function is a ufunc
# Check the type of a function to check if it is a ufunc or not.

# A ufunc should return <class 'numpy.ufunc'>.
import numpy as np
print(type(np.add))

<class 'numpy.ufunc'>


In [32]:
# Check the type of another function: concatenate():
import numpy as np
print(type(np.concatenate))

<class 'function'>


In [36]:
# Use an if statement to check if the function is a ufunc or not:
import numpy as np
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


# Simple Arithmetic Functions :-

In [ ]:
# You could use arithmetic operators + - * / directly between NumPy arrays, 
# but this section discusses an extension of the same where we have functions 
# that can take any array-like objects e.g. lists, tuples etc. and perform 
# arithmetic conditionally.

In [37]:
# Addition
# The add() function sums the content of two arrays, and return the results in a new array.

import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [38]:
# Subtraction
# The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.subtract(arr1, arr2)
print(newarr)

[-10  -1   8  17  26  35]


In [40]:
# Multiplication
# The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print(newarr)

[ 200  420  660  920 1200 1500]


In [42]:
# Division
# The divide() function divides the values from one array with the values from another array, and return the results in a new array.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
newarr = np.divide(arr1, arr2)
print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [43]:
# Power
# The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)
print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


In [48]:
# Remainder
# Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.mod(arr1, arr2)
print(newarr)

arr3 = np.array([10, 20, 30, 40, 50, 60])
arr4 = np.array([4, 5, 5, 3, 2, 13])
newarr1 = np.remainder(arr3, arr4)
print(newarr1)

[ 1  6  3  0  0 27]
[2 0 0 1 0 8]


In [50]:
# Quotient and Mod
# The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

import numpy as np
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])
newarr = np.divmod(arr1, arr2)
print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


In [51]:
# Absolute Values
# Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

import numpy as np
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)

[1 2 1 2 3 4]


# Rounding Decimal Functions :-

In [56]:
# Truncation
# Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

import numpy as np
arr = np.trunc([-3.1666, 3.6667])
print(arr)

# using fix():
arr1 = np.fix([-4.1666, 7.6667])
print(arr1)

[-3.  3.]
[-4.  7.]


In [58]:
# Rounding
# The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

import numpy as np
arr = np.around(3.1666, 2)
print(arr)

3.17


In [59]:
# Floor
# The floor() function rounds off decimal to nearest lower integer.

import numpy as np
arr = np.floor([-3.1666, 3.6667])
print(arr)

[-4.  3.]


In [61]:
# Ceil
# The ceil() function rounds off decimal to nearest upper integer.

import numpy as np
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  4.]


# Log Functions :-

In [62]:
# NumPy provides functions to perform log at the base 2, e and 10.

# We will also explore how we can take log for any base by creating a custom ufunc.

# All of the log functions will place -inf or inf in the elements if the log can not be computed.

In [65]:
# Log at Base 2
# Use the log2() function to perform log at the base 2.

import numpy as np
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [66]:
# Log at Base 10
# Use the log10() function to perform log at the base 10.

import numpy as np
arr = np.arange(1, 10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [67]:
# Natural Log, or Log at Base e
# Use the log() function to perform log at the base e.

import numpy as np
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [68]:
# Log at Any Base
# NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

from math import log
import numpy as np
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

1.7005483074552052


# Set Operations :-

In [ ]:
# A set in mathematics is a collection of unique elements.

# Sets are used for operations involving frequent intersection, union and difference operations.

In [6]:
# Unique() :- We can use NumPy's unique() method to find unique elements from any array.
import numpy as np
arr=np.array([34,56,78,89,34,67,89,90,45,23,45,67,78])
newarray=np.unique(arr)
print(newarray)

[23 34 45 56 67 78 89 90]


In [14]:
# Union1d() :- To find the unique values of two arrays, use the union1d() method.
import numpy as np
x=np.array([10,20,30,40,50,60])
y=np.array([21,10,30,32,43,54])
newarr=np.union1d(x,y)
print(newarr)

[10 20 21 30 32 40 43 50 54 60]


In [15]:
# Intersect1d() :- To find only the values that are present in both arrays, use the intersect1d() method.
import numpy as np
x=np.array([45,56,76,23,12,54])
y=np.array([63,34,55,45,23,56])
newarr=np.intersect1d(x,y)
print(newarr)

[23 45 56]


In [16]:
# setdiff1d() :- To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.
import numpy as np
x=np.array([12,23,34,12,34,56,67,78,56])
y=np.array([78,23,34,43,32,12,54,56,76])
newarr=np.setdiff1d(x,y)
print(newarr)

[67]


In [17]:
# setxor1d() :- To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
import numpy as np
x=np.array([12,23])
y=np.array([12,45,56])
newarr=np.setxor1d(x,y)
print(newarr)

[23 45 56]


# Summations Functions :-

In [18]:
# add() :- Addition is done between two arguments.
import numpy as np
x=np.array([12,23,34,45])
y=np.array([21,32,43,54])
newarr=np.add(x,y)
print(newarr)

[33 55 77 99]


In [19]:
# sum() :- 
import numpy as np
print("1st method :-")
x=np.array([2,4,6,8])
y=np.array([1,3,5,7])
newarr=np.sum([x,y])
print(newarr)
print("2nd method :-")
x=np.array([2,4,6,8])
y=np.array([1,3,5,7])
newarr=np.sum(x)
newarr1=np.sum(y)
newarr2=np.sum(x) + np.sum(y)
print(newarr2)
print("3rd method :-")
x=np.array([2,4,6,8])
y=np.array([1,3,5,7])
newarr=np.sum([x,y],axis=1)
print(newarr)

1st method :-
36
2nd method :-
36
3rd method :-
[20 16]


In [20]:
# cumsum() :- Cummulative sum means partially adding the elements in array.
import numpy as np
x=np.array([1,2,3,4])
newarr=np.cumsum(x)
print(newarr)

[ 1  3  6 10]


# Product Functions :-

In [55]:
# prod() :- To find the product of the elements in an array, use the prod() function.
import numpy as np
x=np.array([1,2,3,4])
newarr=np.prod(x)
print(newarr, "[..because 1*2*3*4=24..]")

24 [..because 1*2*3*4=24..]


In [57]:
# product of two arrays :-
import numpy as np
x=np.array([2,2,2,2])
y=np.array([3,3,3,3])
newarr=np.prod([x,y])
print(newarr, "[..because 2*2*2*2*3*3*3*3=1296..]")

1296 [..because 2*2*2*2*3*3*3*3=1296..]


In [59]:
# product over an axis :- If you specify axis=1, NumPy will return the product of each array.
import numpy as np
x=np.array([2,2,2,2])
y=np.array([3,3,3,3])
newarr=np.prod([x,y],axis=1)
print(newarr, "[..because 2*2*2*2=16..   ..3*3*3*3=81..]")

[16 81] [..because 2*2*2*2=16..   ..3*3*3*3=81..]


In [61]:
# cumprod() :- Cummulative product means taking the product partially.
import numpy as np
x=np.array([5,6,7,8])
newarr=np.cumprod(x)
print(newarr,"[..because 5, 5*6 = 30, 30*7 = 210, 210*8 = 1680..]")

[   5   30  210 1680] [..because 5, 5*6 = 30, 30*7 = 210, 210*8 = 1680..]


# Trigonometric Functions :-

In [3]:
import numpy as np
x = np.sin(np.pi/2)
print(x)

1.0


In [6]:
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [9]:
# Convert Degrees into Radians :-
import numpy as np
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [10]:
# Convert radians into degrees :-
import numpy as np
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[ 90. 180. 270. 360.]


In [13]:
# Finding angles :-
import numpy as np
x = np.arcsin(1.0)
print(x)

1.5707963267948966


In [16]:
# Angles of each value in array :-
import numpy as np
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

[ 1.57079633 -1.57079633  0.10016742]


In [18]:
# Hypoteneous :-
import numpy as np
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

5.0


# Hyperbolic Functions :-

In [20]:
# NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values.

In [22]:
import numpy as np
x = np.sinh(np.pi/2)
print(x)

2.3012989023072947


In [24]:
import numpy as np
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [25]:
# Finding angles :-
import numpy as np
x = np.arcsinh(1.0)
print(x)

0.881373587019543


In [69]:
# angles of each value in array :-
import numpy as np
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

[0.10033535 0.20273255 0.54930614]


# LCM (Lowest Common Factor) Functions :-

In [70]:
# The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [72]:
import numpy as np
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

12


In [74]:
# Finding LCM in Arrays
# To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.

# The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

import numpy as np
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

18


In [76]:
import numpy as np
arr = np.arange(1, 11)
x = np.lcm.reduce(arr)
print(x)

2520


# GCD (Greatest Common Denominator) Functions :-

In [78]:
# The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [80]:
import numpy as np
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)

3


In [81]:
# Finding GCD in Arrays
# To find the Highest Common Factor of all values in an array, you can use the reduce() method.

# The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.

import numpy as np
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

4
